In [2]:
%pip install pandas
%pip install matplotlib

Requirement already satisfied: pandas in /Users/armellelindamatenekakeu/Documents/Projets_Universitaires/GIF-7005/gif-7005_apprentissage_automatique/.venv/lib/python3.14/site-packages (3.1.0)
Requirement already satisfied: numpy>=2.3.3 in /Users/armellelindamatenekakeu/Documents/Projets_Universitaires/GIF-7005/gif-7005_apprentissage_automatique/.venv/lib/python3.14/site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.9.0 in /Users/armellelindamatenekakeu/Documents/Projets_Universitaires/GIF-7005/gif-7005_apprentissage_automatique/.venv/lib/python3.14/site-packages (from pandas) (3.0.0)
Requirement already satisfied: six>=1.6 in /Users/armellelindamatenekakeu/Documents/Projets_Universitaires/GIF-7005/gif-7005_apprentissage_automatique/.venv/lib/python3.14/site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)
Requirement already satisfied: tzdata in /Users/armellelindamatenekakeu/Documents/Projets_Universitaires/GIF-7005/gif-7005_apprentissage_automatique/.venv/lib/python3.14/site-packages (from python-dateutil>=2.9.0->pandas) (2026.5)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: matplotlib in /Users/armellelindamatenekakeu/Documents/Projets_Universitaires/GIF-7005/gif-7005_apprentissage_automatique/.venv/lib/python3.14/site-packages (3.11.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/armellelindamatenekakeu/Documents/Projets_Universitaires/GIF-7005/gif-7005_apprentissage_automatique/.venv/lib/python3.14/site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /Users/armellelindamatenekakeu/Documents/Projets_Universitaires/GIF-7005/gif-7005_apprentissage_automatique/.venv/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /Users/armellelindamatenekakeu/Documents/Projets_Universitaires/GIF-7005/gif-7005_apprentissage_automatique/.venv/lib/python3.14/site-packages (from matplotlib) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/armellelindamatenekakeu/Documents/Projets_Universitaires/GIF-7005/gif-7005_apprentissage_automatique/.venv/lib/python3.14/site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.25 in /Users/armellelindamatenekakeu/Documents/Projets_Universitaires/GIF-7005/gif-7005_apprentissage_automatique/.venv/lib/python3.14/site-packages (from matplotlib) (2.5.4)
Requirement already satisfied: packaging>=20.0 in /Users/armellelindamatenekakeu/Documents/Projets_Universitaires/GIF-7005/gif-7005_apprentissage_automatique/.venv/lib/python3.14/site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in /Users/armellelindamatenekakeu/Documents/Projets_Universitaires/GIF-7005/gif-7005_apprentissage_automatique/.venv/lib/python3.14/site-packages (from matplotlib) (13.0.0)
Requirement already satisfied: pyparsing>=3 in /Users/armellelindamatenekakeu/Documents/Projets_Universitaires/GIF-7005/gif-7005_apprentissage_automatique/.venv/lib/python3.14/site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in /Users/armellelindamatenekakeu/Documents/Projets_Universitaires/GIF-7005/gif-7005_apprentissage_automatique/.venv/lib/python3.14/site-packages (from matplotlib) (3.0.0)
Requirement already satisfied: six>=1.6 in /Users/armellelindamatenekakeu/Documents/Projets_Universitaires/GIF-7005/gif-7005_apprentissage_automatique/.venv/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: tzdata in /Users/armellelindamatenekakeu/Documents/Projets_Universitaires/GIF-7005/gif-7005_apprentissage_automatique/.venv/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib) (2026.5)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

df = pd.read_csv("../data/raw/train.csv")
df.head()

,site_id,patient_id,image_id,laterality,view,age,cancer,biopsy,invasive,BIRADS,implant,density,machine_id,difficult_negative_case
0,2,10006,462822612,L,CC,61.0,0,0,0,NaN,0,NaN,29,False
1,2,10006,1459541791,L,MLO,61.0,0,0,0,NaN,0,NaN,29,False
2,2,10006,1864590858,R,MLO,61.0,0,0,0,NaN,0,NaN,29,False
3,2,10006,1874946579,R,CC,61.0,0,0,0,NaN,0,NaN,29,False
4,2,10011,220375232,L,CC,55.0,0,0,0,0.0,0,NaN,21,True

In [6]:

# Nombre de lignes et de colonnes
print("Dimensions :", df.shape)

# Noms des colonnes
print("Colonnes :", df.columns.tolist())

# Nombre de patientes différentes
print("Patientes :", df["patient_id"].nunique())

# Répartition de la cible au niveau des lignes/images
print(df["cancer"].value_counts())

Dimensions : (54706, 14)
Colonnes : ['site_id', 'patient_id', 'image_id', 'laterality', 'view', 'age', 'cancer', 'biopsy', 'invasive', 'BIRADS', 'implant', 'density', 'machine_id', 'difficult_negative_case']
Patientes : 11913
cancer
0    53548
1     1158
Name: count, dtype: int64

import matplotlib.pyplot as plt

df["cancer"].value_counts().sort_index().plot(kind="bar")
plt.title("Répartition des classes")
plt.xlabel("Classe (0 = cancer, 1 = non cancer)")
plt.ylabel("Nombre d'observations")
plt.axes

## Analyse des étiquettes à différents niveaux

Une patiente peut posséder plusieurs images et deux seins.
Nous allons distinguer les statistiques calculées au niveau
des images, des seins et des patientes.

In [9]:

# 1. Nombre total d'images
n_images = len(df)

# 2. Nombre de patientes distinctes
n_patientes = df["patient_id"].nunique()

# 3. Nombre de seins distincts
n_seins = df[["patient_id", "laterality"]].drop_duplicates().shape[0]

print("Nombre d'images :", n_images)
print("Nombre de patientes distinctes :", n_patientes)
print("Nombre de seins distincts :", n_seins)

Nombre d'images : 54706
Nombre de patientes distinctes : 11913
Nombre de seins distincts : 23826

In [10]:

# Une ligne par patiente et par sein
df_seins = (
    df.groupby(["patient_id", "laterality"])["cancer"]
      .max()
      .reset_index()
)

# Afficher les premières lignes
display(df_seins.head())

# Compter les classes
print(df_seins["cancer"].value_counts())

# Calculer les pourcentages
print(df_seins["cancer"].value_counts(normalize=True) * 100)

   patient_id laterality  cancer
0           5          L       0
1           5          R       0
2          25          L       0
3          25          R       0
4          28          L       0

cancer
0    23334
1      492
Name: count, dtype: int64
cancer
0    97.935029
1     2.064971
Name: proportion, dtype: float64